
name: integration_tests

on:
    workflow_dispatch:
    push: 
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: "17"
            distribution: "temurin"
            cache: maven
        - name: Run integration tests with maven
          run: cd ihntp-backend; mvn failsafe:integration-test
